steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fishing-competition-server', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fishing-competition-server']

options:
  logging: NONE

images:
  - 'gcr.io/$PROJECT_ID/fishing-competition-server'
